name: inspirobot_cli
description: A tool to download images from InspiroBot.
version: 0.1.0
homepage: https://github.com/hacker1024/inspirobot_cli

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  batcher: ^0.1.0
  http: ^0.13.0
  inspirobot: ^1.0.0
  path: ^1.8.0
  progressbar2: ^0.3.1

dev_dependencies:
  lint: ^1.5.3
